name: Auto Merge Dependency Updates

# **What it does**:
#  - automerge-internal: Automatically merge dependabot's pull requests in the internal repository.
#  - close-external: Automatically close dependabot's pull requests in the open-source repository.
# **Why we have it**:
#  - automerge-internal: To keep our dependencies up-to-date, to avoid security issues.
#  - close-external: To avoid duplicating updates against the internal repository.
# **Who does it impact**: It helps docs engineering focus on higher value work.

on:
  pull_request:
    paths:
      - 'package*.json'
      - 'Gemfile*'
      - 'Dockerfile'
      - '.github/workflows/**'
  pull_request_review:
    types:
      - edited
      - submitted

permissions:
  contents: read
  pull-requests: write

jobs:
  automerge-internal:
    if: >-
      ${{
        github.repository == 'github/docs-internal' &&
        github.event.pull_request.number &&
        github.event.pull_request.base.ref == 'main' &&
        github.event.pull_request.user.login == 'dependabot[bot]' &&
        github.event.pull_request.state == 'open'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@cad2ad2510de92ed0c6d06d1b738654f4d4255a2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-actors: dependabot[bot]

  close-external:
    if: >-
      ${{
        github.repository == 'github/docs' &&
        github.event.pull_request.number &&
        github.event.pull_request.base.ref == 'main' &&
        github.event.pull_request.user.login == 'dependabot[bot]' &&
        github.event.pull_request.state == 'open'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Close and comment on the pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr close "$PR_URL"
          gh pr comment "$PR_URL" --body "This dependency update will be handled internally by our engineering team."
